image: Visual Studio 2017

platform:
    - x64

cache:
    #- node_modules
    #- '%USERPROFILE%\.electron'

init:
    - git config --global core.autocrlf input

install:
    - ps: Install-Product node 9.6 x64
    - npm install

# build only on tags
build_script:
    - npm run electron:build
    #- ps: >-
    #      if ($env:APPVEYOR_REPO_TAG -eq "true") {
    #          npm run electron:build
    #      }

test: off
