image: Visual Studio 2017

platform:
    - x64

cache:
    - node_modules
    - '%USERPROFILE%\.electron'

init:
    - git config --global core.autocrlf input

install:
    - ps: Install-Product node 8 x64
    - npm install

build_script:
    - ps: >-
          if ($env:APPVEYOR_REPO_TAG -eq "true") {
              npm run build:electron
          }

test: off
